name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: npm run docker:build
        env:
          GIT_COMMIT: ${{ github.sha }}
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
          VITE_API_URL: ${{ secrets.VITE_API_URL}}

      - name: Push images
        run: npm run docker:push
        env:
          GIT_COMMIT: ${{ github.sha }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN}}
